---
title: "Tracts-Places-Lookup"
author: "Kelly Hondula"
date: "3/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(glue)
library(sf)
library(stringr)
library(tibble)
library(sp)
library(readr)
```

54,858 census tracts in the NFIP data

For each tract
- identify the state it is in (first two digits)
- 
```{r}
data_dir <- "/nfs/khondula-data/projects/river-cities/data"
claims_file <- glue::glue("{data_dir}/NFIP/claims_tracts11.csv")
claims_tracts_df <- vroom::vroom(claims_file, col_types = "c")
claims_tracts <- claims_tracts_df[["tract"]]
claims_census_tract <- claims_tracts[2]
claims_census_tract <- "12131950501"
```

```{r}
get_tract_joins <- function(claims_census_tract, census_scale = "cbsa"){
  
  data_dir <- "/nfs/khondula-data/projects/river-cities/data"
  census_dir <- "/nfs/public-data/census-tiger-2019"
  state_fips <- substr(claims_census_tract, 1, 2)
  
  # read in tracts spatial data and filter to tract
  tracts_dir <- glue("{census_dir}/TRACT")
  tract_file <- glue("{tracts_dir}/tl_2019_{state_fips}_tract.shp")
  tract_sf <- sf::st_read(tract_file) %>%
    dplyr::filter(GEOID == claims_census_tract)
  
  census_scale_dir <- glue("{census_dir}/{str_to_upper(census_scale)}")
  
  census_file <- glue("{census_scale_dir}/tl_2019_us_{census_scale}.shp")
  if(census_scale == "uac"){
    census_file <- glue("{census_scale_dir}/tl_2019_us_{census_scale}10.shp")
  }
  if(census_scale == "place"){
    census_file <- glue("{census_scale_dir}/tl_2019_{state_fips}_{census_scale}.shp")
  }

  census_sf <- sf::st_read(census_file)
  
  # find polygons that tract intersects with
  mat1 <- census_sf %>% sf::st_contains(tract_sf, sparse = FALSE)
  place_wtract <- which(apply(mat1, 1, any))
  places_subset <- census_sf[place_wtract,]
  places_info <- places_subset %>% sf::st_drop_geometry()
  tract_x_place <- places_info %>%
    tibble::add_column(census_tract = claims_census_tract,
                       state = state_fips)
  
  results_dir <- glue("{data_dir}/census-lookups/tract-x-{census_scale}")
  if(!dir.exists(results_dir)){dir.create(results_dir)}
  filepath1 <- glue("{results_dir}/tract_{claims_census_tract}.csv")
  tract_x_place %>% readr::write_csv(filepath1)
  
}

```

```{r}
get_tract_joins(claims_census_tract = claims_tracts[1])

claims_tracts[2:20] %>% 
  purrr::walk(~get_tract_joins(.x))
```

Run on cluster

```{r, eval = FALSE}
library(rslurm)
pars <- data.frame(claims_census_tract = claims_tracts,
                   census_scale = "cbsa",
                   stringsAsFactors = FALSE)

sjob <- slurm_apply(get_tract_joins, 
                    pars, 
                    jobname = 'tracts',
                    # slurm_options = list(partition = "sesync"),
                    nodes = 20, 
                    cpus_per_node = 2,
                    submit = TRUE)

rslurm::get_job_status(sjob)
# rslurm::cancel_slurm(sjob)
```

```{r, eval=FALSE}
glue("{data_dir}/census-lookups/tract-x-{census_scale}") %>%
  list.files() %>% 
  length()

# tracts_x_census_df <- glue("{data_dir}/census-lookups/tract-x-{census_scale}") %>%
#   list.files(full.names = TRUE) %>%
#   purrr::map_df(~read_csv(.x, col_types = c("ccccccccddddcc")))
# View(tracts_x_census_df)
```


```{r}
tract_sf %>% 
  leaflet() %>%
  setView(lng = st_coordinates(st_centroid(tract_sf))[1],
          lat = st_coordinates(st_centroid(tract_sf))[2], zoom = 10) %>%
  addTiles() %>%
  addPolygons(data = cbsa_sf, color = "red", popup = ~NAMELSAD, group = "mets") %>%
  addPolygons(opacity = 1, group = "tract") %>%
  addLayersControl(overlayGroups = c("tract", "mets"))
```



